---
- name: Initial Linux Configuration
  hosts: All 
  become: True

  roles:
    - { role: initial_deployment, when: ansible_os_family == 'Debian'}
    #- { role: initial_deployment_debian, when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'}
