---
- hosts: ubuntu
  become: True
  
  vars_files:
      - ./userlist.yaml

  tasks:
     - name: "The previleged existing checking"
       shell: cat /etc/group | grep privileged
       register: stdout

     - name: "The previleged group creating"
       shell: groupadd privileged
       when: stdout == ''

     - name: "The users creating"
       user:
         name: "{{ item.name }}"
         uid: "{{ item.uid }}"
         groups: "{{ item.groups }}"
         comment: "{{ item.comments }}"
         shell: "{{ item.shell }}"
         password: "{{ item.hash }}"
         generate_ssh_key: yes
         state: present
         update_password: always
       with_items: "{{ user_details }}"
...
