---
    - name: Flush filter
      iptables:
        chain: "{{ item }}"
        flush: yes
      with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]

    - name: Accept lo traffic
      iptables:
        in_interface: lo
        chain: INPUT
        jump: ACCEPT

    - name: Accept ping from public network
      iptables:
        in_interface: ens33
        protocol: icmp
        chain: INPUT
        jump: ACCEPT

    - name: Accept related and established sessions
      iptables:
        chain: INPUT
        ctstate: "{{ item }}"
        jump: ACCEPT
      with_items:
          - RELATED
          - ESTABLISHED

    - name: Permissions for private network
      iptables:
        in_interface: "{{adapters.stdout_lines[1]}}"
        protocol: tcp
        chain: INPUT
        destination_port: "{{ item }}"
        jump: ACCEPT
      with_items:
          - "58257"
          - "6379"

    - name: Drop packages that don't match rules
      iptables:
        chain: "{{ item }}"
        jump: DROP
      with_items:
          - INPUT
          - FORWARD

#    - name: Save current state of the Ubuntu firewall in system file
#      community.general.iptables_state:
#        ip_version: ipv4
#        table: filter
#        state: saved
#        path: /etc/iptables/rules.v4
#      when: ansible_os_family == "Debian"

#    - name: Save current state of the Redhat firewall in system file
#      community.general.iptables_state:
#        ip_version: ipv4
#        table: filter
#        state: saved
#        path: /etc/sysconfig/iptables
#      when: ansible_os_family == "RedHat"    
