---
# tasks file for initial_deployment

- name: "The previleged group creating"
  shell: groupadd privileged
  ignore_errors: yes

- name: "The users creating"
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }}"
    comment: "{{ item.comments }}"
    shell: "{{ item.shell }}"
    password: "{{ item.hash }}"
    state: present
    update_password: always
  with_items: "{{ user_details }}"

- name: Deploy SSH Key
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', 'pubkeys/{{ item.name }}_id_rsa.pub') }}"
    state: present
  with_items: "{{ user_details }}"

- name: "Provide root permissions to previleged group"
  copy:
    dest: "/etc/sudoers.d/privileged"
    content: |
      %privileged ALL=(ALL) ALL
