---
# tasks file for initial_deployment

- name: "ssh/sftp server configuration"
  lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        insertafter: EOF
        line: "{{ item.line }}"
  with_items: "{{ ssh_service_configuration }}"
  notify: Restart sshd.service
